import { readFileSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const htmlPath = join(__dirname, '../../santvani/index.html');
const outPath = join(__dirname, '../src/data/abhangas.ts');

const html = readFileSync(htmlPath, 'utf8');

// Find the abhangas array
const startMarker = 'const abhangas = [';
const startIdx = html.indexOf(startMarker);
if (startIdx === -1) throw new Error('Could not find abhangas array');

// Find the matching closing bracket
let depth = 0;
let arrayStart = html.indexOf('[', startIdx + startMarker.length - 1);
let i = arrayStart;
while (i < html.length) {
  if (html[i] === '[') depth++;
  else if (html[i] === ']') {
    depth--;
    if (depth === 0) break;
  }
  i++;
}
const arrayContent = html.slice(arrayStart, i + 1); // includes [ and ]

// Parse the array
let rawArray;
try {
  rawArray = JSON.parse(arrayContent);
} catch (e) {
  // Try eval-style parse via Function
  rawArray = new Function(`return ${arrayContent}`)();
}

// Add id, meaning, isUserAdded
const abhangas = rawArray.map((item, index) => ({
  id: `bt-${index}`,
  saint: item.saint,
  title: item.title,
  content: item.content,
  meaning: '',
  isUserAdded: false,
}));

console.log(`Extracted ${abhangas.length} abhangas`);

// Sample check
const saints = {};
abhangas.forEach(a => { saints[a.saint] = (saints[a.saint] || 0) + 1; });
console.log('By saint:', saints);

// Write TypeScript file
const tsContent = `// Auto-generated by scripts/extract-data.mjs — do not edit manually
// Total: ${abhangas.length} abhangas
import type { Abhang } from '../types';

export const BUILTIN_ABHANGAS: Abhang[] = ${JSON.stringify(abhangas, null, 0)};
`;

writeFileSync(outPath, tsContent, 'utf8');
console.log(`Written to ${outPath}`);
